### ISSUE TITLE
🐛. Memory Address Violation with C# Tests

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-cpp#193] opened 2021-09-02 16:14 UTC
## Bug Report

Two of the tests have Memory Access Violation on the newest NetStandard tests. These need to be resolved. 

https://github.com/microsoft/electionguard-cpp/blob/2899cf7e455b9322d02de05ab19cbaa0456dc542/bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Tests/TestEncrypt.cs#L12

https://github.com/microsoft/electionguard-cpp/blob/2899cf7e455b9322d02de05ab19cbaa0456dc542/bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Tests/TestBallot.cs#L11

**Comment by AddressXception** [comment] 2021-09-10 17:45
closing as a duplicate of #176

**Closed** 2021-09-10 17:45 UTC
Labels: bug, good first issue, help wanted
